# -*- coding: utf-8 -*-
{
    "name": "Production Custom Module",
    "version": "17.0",
    "category": "Tools",
    "summary": "Auto-generated module",
    "description": "This is an autogenerated module scaffold.",
    "author": 'Your Company',
    "maintainer": "",
    "website": 'https://www.yourcompany.com',
    "depends": ["base","stock","account"],
    
    "data": [
    "security/ir.model.access.csv",
    "security/security.xml",
    "views/siv.xml",
    "views/stock_location.xml",
    "views/fgrn.xml",
    "views/res_config_settings_view.xml",
    "data/sequence.xml",
    ],
    "assets": {},
    "license": "LGPL-3",
    "installable": True,
    "auto_install": False,
    "application": True
}
